sudo: required
services: 
  - docker

before_install: # check the -f flag file path which is different for travis and docker compose
  - docker build -t thivagars/client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thivagars/client npm test -- --coverage # to exit react test with status of 0 if succeed bcoz react test will not exit by default

after_success:
  - docker build -t thivagars/multi-client ./client
  - docker build -t thivagars/multi-nginx ./nginx
  - docker build -t thivagars/multi-server ./server
  - docker build -t thivagars/multi-worker ./worker
  # Login in to the docker cli n env is resolved during run time in travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push thivagars/multi-client
  - docker push thivagars/multi-nginx
  - docker push thivagars/multi-server
  - docker push thivagars/multi-worker

# Commented deloy block
# deploy:
#   provider: elasticbeanstalk 
#   region: us-west-1 # region in aws
#   app: multi-docker # app name
#   env: MultiDocker-env  # app end
#   bucket_name: elasticbeanstalk-us-west-1-306476627547 # S3 bucket name
#   bucket_path: docker-multi # S3 bucket path
#   on:
#     branch: master # start deployement when committed on master branch
#   access_key_id: $AWS_ACCESS_KEY # AWS User access key
#   secret_access_key:
#     secure: $AWS_SECRET_KEY 
#   # secret_access_key: $AWS_SECRET_KEY # if above syntax is not working, Secret key for AWS user